// Format: clue shown to player, precise lat/lng of the feature, label shown in results
const QUESTIONS = [

  // ── Europe — Landmarks ───────────────────────────────────────────────────
  { clue: "Eiffel Tower, Paris, France",               lat: 48.8584,  lng: 2.2945,   label: "Eiffel Tower, Paris" },
  { clue: "Louvre Museum, Paris, France",              lat: 48.8606,  lng: 2.3376,   label: "Louvre Museum, Paris" },
  { clue: "Notre-Dame Cathedral, Paris, France",       lat: 48.8530,  lng: 2.3499,   label: "Notre-Dame, Paris" },
  { clue: "Arc de Triomphe, Paris, France",            lat: 48.8738,  lng: 2.2950,   label: "Arc de Triomphe, Paris" },
  { clue: "Sacré-Cœur Basilica, Paris, France",       lat: 48.8867,  lng: 2.3431,   label: "Sacré-Cœur, Paris" },
  { clue: "Palace of Versailles, Versailles, France",  lat: 48.8049,  lng: 2.1204,   label: "Palace of Versailles" },
  { clue: "Mont-Saint-Michel Abbey, Normandy, France", lat: 48.6360,  lng: -1.5115,  label: "Mont-Saint-Michel, France" },
  { clue: "Colosseum, Rome, Italy",                    lat: 41.8902,  lng: 12.4922,  label: "Colosseum, Rome" },
  { clue: "Vatican (St. Peter's Basilica), Rome, Italy", lat: 41.9022, lng: 12.4539, label: "St. Peter's Basilica, Vatican" },
  { clue: "Trevi Fountain, Rome, Italy",               lat: 41.9009,  lng: 12.4833,  label: "Trevi Fountain, Rome" },
  { clue: "Pantheon, Rome, Italy",                     lat: 41.8986,  lng: 12.4769,  label: "Pantheon, Rome" },
  { clue: "Leaning Tower of Pisa, Pisa, Italy",        lat: 43.7230,  lng: 10.3966,  label: "Leaning Tower of Pisa" },
  { clue: "Florence Cathedral (Duomo), Florence, Italy", lat: 43.7731, lng: 11.2560, label: "Florence Cathedral" },
  { clue: "Uffizi Gallery, Florence, Italy",           lat: 43.7678,  lng: 11.2553,  label: "Uffizi Gallery, Florence" },
  { clue: "Doge's Palace, Venice, Italy",              lat: 45.4337,  lng: 12.3393,  label: "Doge's Palace, Venice" },
  { clue: "Rialto Bridge, Venice, Italy",              lat: 45.4381,  lng: 12.3359,  label: "Rialto Bridge, Venice" },
  { clue: "Pompeii Ruins, Pompeii, Italy",             lat: 40.7506,  lng: 14.4897,  label: "Pompeii Ruins" },
  { clue: "Mount Vesuvius Crater, Naples, Italy",      lat: 40.8210,  lng: 14.4260,  label: "Vesuvius, Naples" },
  { clue: "Sagrada Família, Barcelona, Spain",         lat: 41.4036,  lng: 2.1744,   label: "Sagrada Família, Barcelona" },
  { clue: "Park Güell, Barcelona, Spain",              lat: 41.4145,  lng: 2.1527,   label: "Park Güell, Barcelona" },
  { clue: "Alhambra Palace, Granada, Spain",           lat: 37.1760,  lng: -3.5881,  label: "Alhambra, Granada" },
  { clue: "Prado Museum, Madrid, Spain",               lat: 40.4138,  lng: -3.6921,  label: "Prado Museum, Madrid" },
  { clue: "Santiago de Compostela Cathedral, Spain",   lat: 42.8805,  lng: -8.5446,  label: "Santiago de Compostela Cathedral" },
  { clue: "Acropolis of Athens, Athens, Greece",       lat: 37.9715,  lng: 23.7267,  label: "Acropolis, Athens" },
  { clue: "Parthenon, Athens, Greece",                 lat: 37.9715,  lng: 23.7267,  label: "Parthenon, Athens" },
  { clue: "Santorini Caldera, Fira, Greece",           lat: 36.4178,  lng: 25.4365,  label: "Santorini Caldera, Greece" },
  { clue: "Meteora Monasteries, Thessaly, Greece",     lat: 39.7217,  lng: 21.6306,  label: "Meteora Monasteries, Greece" },
  { clue: "Knossos Palace, Crete, Greece",             lat: 35.2981,  lng: 25.1631,  label: "Knossos Palace, Crete" },
  { clue: "Buckingham Palace, London, UK",             lat: 51.5014,  lng: -0.1419,  label: "Buckingham Palace, London" },
  { clue: "Big Ben (Elizabeth Tower), London, UK",     lat: 51.5007,  lng: -0.1246,  label: "Big Ben, London" },
  { clue: "Tower of London, London, UK",               lat: 51.5081,  lng: -0.0759,  label: "Tower of London" },
  { clue: "Tower Bridge, London, UK",                  lat: 51.5055,  lng: -0.0754,  label: "Tower Bridge, London" },
  { clue: "Stonehenge, Wiltshire, UK",                 lat: 51.1789,  lng: -1.8262,  label: "Stonehenge, Wiltshire" },
  { clue: "Edinburgh Castle, Edinburgh, Scotland",     lat: 55.9486,  lng: -3.2008,  label: "Edinburgh Castle, Scotland" },
  { clue: "Loch Ness, Scottish Highlands, UK",         lat: 57.2226,  lng: -4.4990,  label: "Loch Ness, Scotland" },
  { clue: "Brandenburg Gate, Berlin, Germany",         lat: 52.5163,  lng: 13.3777,  label: "Brandenburg Gate, Berlin" },
  { clue: "Neuschwanstein Castle, Bavaria, Germany",   lat: 47.5576,  lng: 10.7498,  label: "Neuschwanstein Castle, Germany" },
  { clue: "Cologne Cathedral, Cologne, Germany",       lat: 50.9413,  lng: 6.9583,   label: "Cologne Cathedral, Germany" },
  { clue: "Reichstag Building, Berlin, Germany",       lat: 52.5186,  lng: 13.3762,  label: "Reichstag, Berlin" },
  { clue: "Checkpoint Charlie, Berlin, Germany",       lat: 52.5075,  lng: 13.3903,  label: "Checkpoint Charlie, Berlin" },
  { clue: "Bavarian Alps (Zugspitze), Bavaria, Germany", lat: 47.4211, lng: 10.9853, label: "Zugspitze Summit, Germany" },
  { clue: "Amsterdam Canals (Herengracht), Amsterdam, Netherlands", lat: 52.3728, lng: 4.8936, label: "Herengracht, Amsterdam" },
  { clue: "Anne Frank House, Amsterdam, Netherlands",  lat: 52.3752,  lng: 4.8840,   label: "Anne Frank House, Amsterdam" },
  { clue: "Keukenhof Gardens, Lisse, Netherlands",     lat: 52.2703,  lng: 4.5469,   label: "Keukenhof Gardens, Netherlands" },
  { clue: "Atomium, Brussels, Belgium",                lat: 50.8947,  lng: 4.3415,   label: "Atomium, Brussels" },
  { clue: "Manneken Pis, Brussels, Belgium",           lat: 50.8451,  lng: 4.3498,   label: "Manneken Pis, Brussels" },
  { clue: "Chateau de Chillon, Montreux, Switzerland", lat: 46.4142,  lng: 6.9278,   label: "Château de Chillon, Switzerland" },
  { clue: "Matterhorn Peak, Zermatt, Switzerland",     lat: 45.9766,  lng: 7.6586,   label: "Matterhorn, Switzerland" },
  { clue: "Jungfraujoch Railway Station, Alps, Switzerland", lat: 46.5474, lng: 7.9857, label: "Jungfraujoch, Switzerland" },
  { clue: "Hallstatt Village, Austria",                lat: 47.5622,  lng: 13.6493,  label: "Hallstatt, Austria" },
  { clue: "Schönbrunn Palace, Vienna, Austria",        lat: 48.1845,  lng: 16.3122,  label: "Schönbrunn Palace, Vienna" },
  { clue: "Prague Castle, Prague, Czech Republic",     lat: 50.0906,  lng: 14.4006,  label: "Prague Castle, Czech Republic" },
  { clue: "Charles Bridge, Prague, Czech Republic",    lat: 50.0865,  lng: 14.4114,  label: "Charles Bridge, Prague" },
  { clue: "Buda Castle, Budapest, Hungary",            lat: 47.4960,  lng: 19.0399,  label: "Buda Castle, Budapest" },
  { clue: "Fisherman's Bastion, Budapest, Hungary",    lat: 47.5019,  lng: 19.0343,  label: "Fisherman's Bastion, Budapest" },
  { clue: "Wawel Castle, Kraków, Poland",              lat: 50.0542,  lng: 19.9352,  label: "Wawel Castle, Kraków" },
  { clue: "Auschwitz-Birkenau Memorial, Oświęcim, Poland", lat: 50.0343, lng: 19.1784, label: "Auschwitz Memorial, Poland" },
  { clue: "Hagia Sophia, Istanbul, Turkey",            lat: 41.0086,  lng: 28.9802,  label: "Hagia Sophia, Istanbul" },
  { clue: "Blue Mosque, Istanbul, Turkey",             lat: 41.0054,  lng: 28.9768,  label: "Blue Mosque, Istanbul" },
  { clue: "Galata Tower, Istanbul, Turkey",            lat: 41.0256,  lng: 28.9742,  label: "Galata Tower, Istanbul" },
  { clue: "Mount Olympus, Thessaly, Greece",           lat: 40.0853,  lng: 22.3583,  label: "Mount Olympus, Greece" },
  { clue: "Eifel Tower — wait, that's Eiffel. Click it anyway!", lat: 48.8584, lng: 2.2945, label: "Eiffel Tower, Paris" },

  // ── Middle East & Central Asia ───────────────────────────────────────────
  { clue: "Petra (Rose City), Ma'an, Jordan",          lat: 30.3285,  lng: 35.4444,  label: "Petra, Jordan" },
  { clue: "Dome of the Rock, Jerusalem, Israel",       lat: 31.7781,  lng: 35.2354,  label: "Dome of the Rock, Jerusalem" },
  { clue: "Western Wall, Jerusalem, Israel",           lat: 31.7767,  lng: 35.2345,  label: "Western Wall, Jerusalem" },
  { clue: "Masada Fortress, Judean Desert, Israel",    lat: 31.3155,  lng: 35.3536,  label: "Masada Fortress, Israel" },
  { clue: "Dead Sea Shore, Jordan/Israel",             lat: 31.5590,  lng: 35.4732,  label: "Dead Sea Shoreline" },
  { clue: "Burj Khalifa, Dubai, UAE",                  lat: 25.1972,  lng: 55.2744,  label: "Burj Khalifa, Dubai" },
  { clue: "Palm Jumeirah, Dubai, UAE",                 lat: 25.1124,  lng: 55.1390,  label: "Palm Jumeirah, Dubai" },
  { clue: "Sheikh Zayed Grand Mosque, Abu Dhabi, UAE", lat: 24.4128,  lng: 54.4750,  label: "Grand Mosque, Abu Dhabi" },
  { clue: "Burj Al Arab Hotel, Dubai, UAE",            lat: 25.1412,  lng: 55.1853,  label: "Burj Al Arab, Dubai" },
  { clue: "Persepolis Ruins, Shiraz, Iran",            lat: 29.9348,  lng: 52.8892,  label: "Persepolis, Iran" },
  { clue: "Naqsh-e Jahan Square, Isfahan, Iran",       lat: 32.6573,  lng: 51.6767,  label: "Naqsh-e Jahan Square, Isfahan" },
  { clue: "Topkapi Palace, Istanbul, Turkey",          lat: 41.0115,  lng: 28.9833,  label: "Topkapi Palace, Istanbul" },
  { clue: "Ephesus Ancient City, İzmir, Turkey",       lat: 37.9417,  lng: 27.3417,  label: "Ephesus, Turkey" },
  { clue: "Cappadocia (Fairy Chimneys), Göreme, Turkey", lat: 38.6431, lng: 34.8297, label: "Cappadocia, Turkey" },
  { clue: "Pamukkale Thermal Pools, Denizli, Turkey",  lat: 37.9214,  lng: 29.1206,  label: "Pamukkale, Turkey" },
  { clue: "Palmyra Ruins, Tadmur, Syria",              lat: 34.5503,  lng: 38.2666,  label: "Palmyra, Syria" },
  { clue: "Baalbek Temples, Baalbek, Lebanon",         lat: 34.0042,  lng: 36.2114,  label: "Baalbek, Lebanon" },
  { clue: "Registan Square, Samarkand, Uzbekistan",    lat: 39.6553,  lng: 66.9758,  label: "Registan Square, Samarkand" },
  { clue: "Khiva Old City (Itchan Kala), Uzbekistan",  lat: 41.3790,  lng: 60.3608,  label: "Khiva Old City, Uzbekistan" },

  // ── Africa ───────────────────────────────────────────────────────────────
  { clue: "Pyramids of Giza, Giza, Egypt",             lat: 29.9792,  lng: 31.1342,  label: "Pyramids of Giza, Egypt" },
  { clue: "Great Sphinx of Giza, Giza, Egypt",         lat: 29.9753,  lng: 31.1376,  label: "Great Sphinx, Giza" },
  { clue: "Valley of the Kings, Luxor, Egypt",         lat: 25.7402,  lng: 32.6014,  label: "Valley of the Kings, Luxor" },
  { clue: "Karnak Temple Complex, Luxor, Egypt",       lat: 25.7188,  lng: 32.6573,  label: "Karnak Temple, Luxor" },
  { clue: "Abu Simbel Temples, Aswan, Egypt",          lat: 22.3372,  lng: 31.6258,  label: "Abu Simbel, Egypt" },
  { clue: "Victoria Falls, Livingstone, Zambia",       lat: -17.9243, lng: 25.8572,  label: "Victoria Falls, Zambia/Zimbabwe" },
  { clue: "Mount Kilimanjaro Summit, Tanzania",        lat: -3.0674,  lng: 37.3556,  label: "Kilimanjaro Summit, Tanzania" },
  { clue: "Ngorongoro Crater, Arusha, Tanzania",       lat: -3.2089,  lng: 35.5000,  label: "Ngorongoro Crater, Tanzania" },
  { clue: "Serengeti Migration Plains, Tanzania",      lat: -2.3333,  lng: 34.8333,  label: "Serengeti Plains, Tanzania" },
  { clue: "Mount Kenya Peak, Kenya",                   lat: -0.1521,  lng: 37.3084,  label: "Mount Kenya" },
  { clue: "Masai Mara Game Reserve, Narok, Kenya",     lat: -1.5096,  lng: 35.1437,  label: "Masai Mara, Kenya" },
  { clue: "Table Mountain, Cape Town, South Africa",   lat: -33.9628, lng: 18.4098,  label: "Table Mountain, Cape Town" },
  { clue: "Robben Island, Cape Town, South Africa",    lat: -33.8070, lng: 18.3668,  label: "Robben Island, South Africa" },
  { clue: "Cape of Good Hope, Cape Town, South Africa", lat: -34.3568, lng: 18.4734, label: "Cape of Good Hope" },
  { clue: "Okavango Delta, Maun, Botswana",            lat: -19.3087, lng: 22.8628,  label: "Okavango Delta, Botswana" },
  { clue: "Great Zimbabwe Ruins, Masvingo, Zimbabwe",  lat: -20.2671, lng: 30.9336,  label: "Great Zimbabwe Ruins" },
  { clue: "Rock-Hewn Churches, Lalibela, Ethiopia",    lat: 12.0318,  lng: 39.0462,  label: "Lalibela Churches, Ethiopia" },
  { clue: "Djemaa el-Fna Square, Marrakech, Morocco",  lat: 31.6258,  lng: -7.9891,  label: "Djemaa el-Fna, Marrakech" },
  { clue: "Hassan II Mosque, Casablanca, Morocco",     lat: 33.6084,  lng: -7.6326,  label: "Hassan II Mosque, Casablanca" },
  { clue: "Medina of Fez, Fez, Morocco",               lat: 34.0646,  lng: -4.9755,  label: "Medina of Fez, Morocco" },
  { clue: "Erg Chebbi Sand Dunes, Merzouga, Morocco",  lat: 31.1349,  lng: -3.9796,  label: "Erg Chebbi Dunes, Morocco" },
  { clue: "Sahara Desert at Timbuktu, Mali",           lat: 16.7666,  lng: -3.0026,  label: "Timbuktu, Mali — Sahara Edge" },
  { clue: "Ruins of Carthage, Tunis, Tunisia",         lat: 36.8528,  lng: 10.3233,  label: "Carthage Ruins, Tunisia" },
  { clue: "Madagascar Rainforest, Ranomafana, Madagascar", lat: -21.2611, lng: 47.4431, label: "Ranomafana NP, Madagascar" },

  // ── South Asia ───────────────────────────────────────────────────────────
  { clue: "Taj Mahal, Agra, India",                    lat: 27.1751,  lng: 78.0421,  label: "Taj Mahal, Agra" },
  { clue: "Red Fort, Delhi, India",                    lat: 28.6562,  lng: 77.2410,  label: "Red Fort, Delhi" },
  { clue: "India Gate, New Delhi, India",              lat: 28.6129,  lng: 77.2295,  label: "India Gate, New Delhi" },
  { clue: "Qutb Minar, New Delhi, India",              lat: 28.5245,  lng: 77.1855,  label: "Qutb Minar, Delhi" },
  { clue: "Hawa Mahal (Palace of Winds), Jaipur, India", lat: 26.9239, lng: 75.8267, label: "Hawa Mahal, Jaipur" },
  { clue: "Amber Fort, Jaipur, India",                 lat: 26.9855,  lng: 75.8513,  label: "Amber Fort, Jaipur" },
  { clue: "Golden Temple, Amritsar, India",            lat: 31.6200,  lng: 74.8765,  label: "Golden Temple, Amritsar" },
  { clue: "Gateway of India, Mumbai, India",           lat: 18.9220,  lng: 72.8347,  label: "Gateway of India, Mumbai" },
  { clue: "Charminar, Hyderabad, India",               lat: 17.3616,  lng: 78.4747,  label: "Charminar, Hyderabad" },
  { clue: "Mysore Palace, Mysore, India",              lat: 12.3052,  lng: 76.6551,  label: "Mysore Palace, India" },
  { clue: "Meenakshi Temple, Madurai, India",          lat: 9.9195,   lng: 78.1193,  label: "Meenakshi Temple, Madurai" },
  { clue: "Ajanta Caves, Aurangabad, India",           lat: 20.5519,  lng: 75.7033,  label: "Ajanta Caves, India" },
  { clue: "Ellora Caves, Aurangabad, India",           lat: 20.0268,  lng: 75.1791,  label: "Ellora Caves, India" },
  { clue: "Victoria Memorial, Kolkata, India",         lat: 22.5448,  lng: 88.3426,  label: "Victoria Memorial, Kolkata" },
  { clue: "Mount Everest Base Camp, Nepal",            lat: 28.0054,  lng: 86.8567,  label: "Everest Base Camp, Nepal" },
  { clue: "Boudhanath Stupa, Kathmandu, Nepal",        lat: 27.7215,  lng: 85.3620,  label: "Boudhanath Stupa, Kathmandu" },
  { clue: "Pashupatinath Temple, Kathmandu, Nepal",    lat: 27.7109,  lng: 85.3488,  label: "Pashupatinath, Kathmandu" },
  { clue: "Annapurna Base Camp, Nepal",                lat: 28.5307,  lng: 83.8769,  label: "Annapurna Base Camp, Nepal" },
  { clue: "Sigiriya Rock Fortress, Sri Lanka",         lat: 7.9570,   lng: 80.7603,  label: "Sigiriya Rock, Sri Lanka" },
  { clue: "Temple of the Tooth, Kandy, Sri Lanka",     lat: 7.2936,   lng: 80.6413,  label: "Temple of the Tooth, Kandy" },
  { clue: "Mohenjo-Daro Ruins, Sindh, Pakistan",       lat: 27.3241,  lng: 68.1375,  label: "Mohenjo-Daro, Pakistan" },
  { clue: "K2 Summit, Gilgit-Baltistan, Pakistan",     lat: 35.8825,  lng: 76.5133,  label: "K2 Summit, Pakistan/China" },
  { clue: "Badshahi Mosque, Lahore, Pakistan",         lat: 31.5881,  lng: 74.3107,  label: "Badshahi Mosque, Lahore" },
  { clue: "Potala Palace, Lhasa, Tibet",               lat: 29.6579,  lng: 91.1172,  label: "Potala Palace, Lhasa" },

  // ── East & Southeast Asia ────────────────────────────────────────────────
  { clue: "Great Wall of China (Badaling), Beijing, China", lat: 40.3594, lng: 116.0173, label: "Great Wall, Badaling, China" },
  { clue: "Forbidden City, Beijing, China",            lat: 39.9163,  lng: 116.3972,  label: "Forbidden City, Beijing" },
  { clue: "Temple of Heaven, Beijing, China",          lat: 39.8822,  lng: 116.4066,  label: "Temple of Heaven, Beijing" },
  { clue: "Summer Palace, Beijing, China",             lat: 39.9999,  lng: 116.2755,  label: "Summer Palace, Beijing" },
  { clue: "Terracotta Army, Xi'an, China",             lat: 34.3853,  lng: 109.2735,  label: "Terracotta Army, Xi'an" },
  { clue: "Li River Karst Peaks, Guilin, China",       lat: 24.3192,  lng: 110.5992,  label: "Li River Karst Peaks, Guilin" },
  { clue: "The Bund Waterfront, Shanghai, China",      lat: 31.2397,  lng: 121.4900,  label: "The Bund, Shanghai" },
  { clue: "Oriental Pearl Tower, Shanghai, China",     lat: 31.2396,  lng: 121.4995,  label: "Oriental Pearl Tower, Shanghai" },
  { clue: "Zhangjiajie Glass Bridge, Hunan, China",    lat: 29.3247,  lng: 110.4345,  label: "Zhangjiajie, Hunan, China" },
  { clue: "Yellow Mountain (Huangshan), Anhui, China", lat: 30.1340,  lng: 118.1689,  label: "Huangshan, Anhui, China" },
  { clue: "Mount Fuji Summit, Yamanashi, Japan",       lat: 35.3606,  lng: 138.7274,  label: "Mount Fuji, Japan" },
  { clue: "Senso-ji Temple, Tokyo, Japan",             lat: 35.7148,  lng: 139.7967,  label: "Senso-ji Temple, Tokyo" },
  { clue: "Shibuya Crossing, Tokyo, Japan",            lat: 35.6595,  lng: 139.7004,  label: "Shibuya Crossing, Tokyo" },
  { clue: "Tokyo Skytree, Tokyo, Japan",               lat: 35.7101,  lng: 139.8107,  label: "Tokyo Skytree" },
  { clue: "Fushimi Inari Shrine, Kyoto, Japan",        lat: 34.9671,  lng: 135.7727,  label: "Fushimi Inari, Kyoto" },
  { clue: "Kinkaku-ji (Golden Pavilion), Kyoto, Japan", lat: 35.0394, lng: 135.7292,  label: "Kinkaku-ji, Kyoto" },
  { clue: "Arashiyama Bamboo Grove, Kyoto, Japan",     lat: 35.0168,  lng: 135.6714,  label: "Arashiyama Bamboo Grove, Kyoto" },
  { clue: "Hiroshima Peace Memorial, Hiroshima, Japan", lat: 34.3953, lng: 132.4534,  label: "Hiroshima Peace Memorial" },
  { clue: "Todai-ji Temple, Nara, Japan",              lat: 34.6888,  lng: 135.8398,  label: "Todai-ji Temple, Nara" },
  { clue: "Himeji Castle, Himeji, Japan",              lat: 34.8394,  lng: 134.6939,  label: "Himeji Castle, Japan" },
  { clue: "Gyeongbokgung Palace, Seoul, South Korea",  lat: 37.5796,  lng: 126.9770,  label: "Gyeongbokgung Palace, Seoul" },
  { clue: "N Seoul Tower, Seoul, South Korea",         lat: 37.5512,  lng: 126.9882,  label: "N Seoul Tower, South Korea" },
  { clue: "Bulguksa Temple, Gyeongju, South Korea",    lat: 35.7891,  lng: 129.3319,  label: "Bulguksa Temple, Gyeongju" },
  { clue: "Jeju Island (Hallasan Volcano), South Korea", lat: 33.3617, lng: 126.5292, label: "Hallasan, Jeju Island" },
  { clue: "Angkor Wat Temple, Siem Reap, Cambodia",    lat: 13.4125,  lng: 103.8670,  label: "Angkor Wat, Cambodia" },
  { clue: "Angkor Thom, Siem Reap, Cambodia",          lat: 13.4414,  lng: 103.8590,  label: "Angkor Thom, Cambodia" },
  { clue: "Halong Bay Karsts, Quảng Ninh, Vietnam",    lat: 20.9101,  lng: 107.1839,  label: "Halong Bay, Vietnam" },
  { clue: "Hội An Ancient Town, Quảng Nam, Vietnam",   lat: 15.8801,  lng: 108.3380,  label: "Hội An, Vietnam" },
  { clue: "My Son Sanctuary (Cham ruins), Vietnam",    lat: 15.7650,  lng: 108.1250,  label: "My Son Sanctuary, Vietnam" },
  { clue: "Petronas Twin Towers, Kuala Lumpur, Malaysia", lat: 3.1579, lng: 101.7116, label: "Petronas Towers, Kuala Lumpur" },
  { clue: "Batu Caves, Kuala Lumpur, Malaysia",        lat: 3.2379,   lng: 101.6840,  label: "Batu Caves, Malaysia" },
  { clue: "Marina Bay Sands, Singapore",               lat: 1.2838,   lng: 103.8607,  label: "Marina Bay Sands, Singapore" },
  { clue: "Gardens by the Bay, Singapore",             lat: 1.2816,   lng: 103.8636,  label: "Gardens by the Bay, Singapore" },
  { clue: "Borobudur Temple, Magelang, Indonesia",     lat: -7.6079,  lng: 110.2038,  label: "Borobudur Temple, Java" },
  { clue: "Prambanan Temple, Yogyakarta, Indonesia",   lat: -7.7520,  lng: 110.4915,  label: "Prambanan Temple, Java" },
  { clue: "Bali Rice Terraces (Tegalalang), Ubud, Indonesia", lat: -8.4312, lng: 115.2762, label: "Tegalalang Rice Terraces, Bali" },
  { clue: "Mount Bromo Volcano, East Java, Indonesia", lat: -7.9425,  lng: 112.9530,  label: "Mount Bromo, Java" },
  { clue: "Komodo Island (dragon habitat), Indonesia", lat: -8.5497,  lng: 119.4765,  label: "Komodo Island, Indonesia" },
  { clue: "Intramuros Walled City, Manila, Philippines", lat: 14.5893, lng: 120.9742, label: "Intramuros, Manila" },
  { clue: "Chocolate Hills, Bohol, Philippines",       lat: 9.7940,   lng: 124.1756,  label: "Chocolate Hills, Bohol" },
  { clue: "Mayon Volcano, Legazpi, Philippines",       lat: 13.2575,  lng: 123.6857,  label: "Mayon Volcano, Philippines" },
  { clue: "Shwedagon Pagoda, Yangon, Myanmar",         lat: 16.7985,  lng: 96.1496,   label: "Shwedagon Pagoda, Yangon" },
  { clue: "Bagan Temples, Mandalay, Myanmar",          lat: 21.1717,  lng: 94.8585,   label: "Bagan Temples, Myanmar" },
  { clue: "Wat Phra Kaew, Bangkok, Thailand",          lat: 13.7516,  lng: 100.4929,  label: "Wat Phra Kaew, Bangkok" },
  { clue: "Wat Pho (Reclining Buddha), Bangkok, Thailand", lat: 13.7465, lng: 100.4929, label: "Wat Pho, Bangkok" },
  { clue: "Wat Arun (Temple of Dawn), Bangkok, Thailand", lat: 13.7438, lng: 100.4871, label: "Wat Arun, Bangkok" },
  { clue: "Phi Phi Islands, Krabi, Thailand",          lat: 7.7407,   lng: 98.7784,   label: "Phi Phi Islands, Thailand" },
  { clue: "Chiang Mai Old City, Chiang Mai, Thailand", lat: 18.7883,  lng: 98.9853,   label: "Chiang Mai Old City, Thailand" },

  // ── Americas ─────────────────────────────────────────────────────────────
  { clue: "Statue of Liberty, New York City, USA",     lat: 40.6892,  lng: -74.0445,  label: "Statue of Liberty, New York" },
  { clue: "Empire State Building, New York City, USA", lat: 40.7484,  lng: -73.9857,  label: "Empire State Building, NYC" },
  { clue: "Times Square, New York City, USA",          lat: 40.7580,  lng: -73.9855,  label: "Times Square, New York" },
  { clue: "Brooklyn Bridge, New York City, USA",       lat: 40.7061,  lng: -73.9969,  label: "Brooklyn Bridge, NYC" },
  { clue: "Central Park, New York City, USA",          lat: 40.7851,  lng: -73.9683,  label: "Central Park, NYC" },
  { clue: "One World Trade Center, New York City, USA", lat: 40.7130, lng: -74.0134,  label: "One World Trade Center, NYC" },
  { clue: "White House, Washington D.C., USA",         lat: 38.8977,  lng: -77.0365,  label: "White House, Washington DC" },
  { clue: "Lincoln Memorial, Washington D.C., USA",    lat: 38.8893,  lng: -77.0502,  label: "Lincoln Memorial, DC" },
  { clue: "Washington Monument, D.C., USA",            lat: 38.8895,  lng: -77.0353,  label: "Washington Monument, DC" },
  { clue: "US Capitol Building, Washington D.C., USA", lat: 38.8899,  lng: -77.0091,  label: "US Capitol, Washington DC" },
  { clue: "Smithsonian National Mall, Washington D.C., USA", lat: 38.8888, lng: -77.0260, label: "Smithsonian Mall, DC" },
  { clue: "Golden Gate Bridge, San Francisco, USA",    lat: 37.8199,  lng: -122.4783, label: "Golden Gate Bridge, San Francisco" },
  { clue: "Alcatraz Island, San Francisco, USA",       lat: 37.8267,  lng: -122.4230, label: "Alcatraz Island, San Francisco" },
  { clue: "Hollywood Sign, Los Angeles, USA",          lat: 34.1341,  lng: -118.3215, label: "Hollywood Sign, Los Angeles" },
  { clue: "Las Vegas Strip (Bellagio), Nevada, USA",   lat: 36.1126,  lng: -115.1767, label: "Bellagio, Las Vegas" },
  { clue: "Space Needle, Seattle, USA",                lat: 47.6205,  lng: -122.3493, label: "Space Needle, Seattle" },
  { clue: "Willis Tower, Chicago, USA",                lat: 41.8789,  lng: -87.6359,  label: "Willis Tower, Chicago" },
  { clue: "Millennium Park (Cloud Gate), Chicago, USA", lat: 41.8827,  lng: -87.6233, label: "Cloud Gate, Millennium Park, Chicago" },
  { clue: "French Quarter, New Orleans, USA",          lat: 29.9584,  lng: -90.0644,  label: "French Quarter, New Orleans" },
  { clue: "Mount Rushmore, Keystone, South Dakota, USA", lat: 43.8791, lng: -103.4591, label: "Mount Rushmore, South Dakota" },
  { clue: "Grand Canyon South Rim, Arizona, USA",      lat: 36.0565,  lng: -112.1251, label: "Grand Canyon South Rim" },
  { clue: "Monument Valley, Arizona/Utah, USA",        lat: 36.9830,  lng: -110.0985, label: "Monument Valley, USA" },
  { clue: "Yellowstone Caldera, Wyoming, USA",         lat: 44.4280,  lng: -110.5885, label: "Yellowstone Caldera, Wyoming" },
  { clue: "Old Faithful Geyser, Yellowstone, USA",     lat: 44.4605,  lng: -110.8282, label: "Old Faithful, Yellowstone" },
  { clue: "Niagara Falls (Horseshoe), Ontario, Canada", lat: 43.0781,  lng: -79.0748, label: "Horseshoe Falls, Niagara" },
  { clue: "CN Tower, Toronto, Canada",                 lat: 43.6426,  lng: -79.3871,  label: "CN Tower, Toronto" },
  { clue: "Banff National Park (Lake Louise), Alberta, Canada", lat: 51.4165, lng: -116.1772, label: "Lake Louise, Banff, Canada" },
  { clue: "Château Frontenac, Québec City, Canada",    lat: 46.8197,  lng: -71.2047,  label: "Château Frontenac, Québec" },
  { clue: "Parliament Hill, Ottawa, Canada",           lat: 45.4236,  lng: -75.7009,  label: "Parliament Hill, Ottawa" },
  { clue: "Chichen Itza Pyramid, Yucatán, Mexico",     lat: 20.6843,  lng: -88.5678,  label: "Chichen Itza, Mexico" },
  { clue: "Teotihuacan Pyramids, Mexico City, Mexico", lat: 19.6925,  lng: -98.8438,  label: "Teotihuacan, Mexico" },
  { clue: "Palenque Ruins, Chiapas, Mexico",           lat: 17.4838,  lng: -92.0457,  label: "Palenque Ruins, Mexico" },
  { clue: "Chaco Canyon Pueblo Bonito, New Mexico, USA", lat: 36.0608, lng: -107.9585, label: "Pueblo Bonito, Chaco Canyon" },
  { clue: "Machu Picchu Citadel, Cusco, Peru",         lat: -13.1631, lng: -72.5450,  label: "Machu Picchu, Peru" },
  { clue: "Nazca Lines (Hummingbird), Ica, Peru",      lat: -14.6961, lng: -75.1483,  label: "Nazca Lines, Peru" },
  { clue: "Lake Titicaca (Uros Floating Islands), Puno, Peru", lat: -15.8102, lng: -69.9753, label: "Lake Titicaca, Peru/Bolivia" },
  { clue: "Tiwanaku Ruins, La Paz, Bolivia",           lat: -16.5547, lng: -68.6735,  label: "Tiwanaku, Bolivia" },
  { clue: "Uyuni Salt Flats, Potosí, Bolivia",         lat: -20.1338, lng: -67.4891,  label: "Salar de Uyuni, Bolivia" },
  { clue: "Christ the Redeemer, Rio de Janeiro, Brazil", lat: -22.9519, lng: -43.2105, label: "Christ the Redeemer, Rio" },
  { clue: "Iguazu Falls (Garganta del Diablo), Misiones, Argentina", lat: -25.6953, lng: -54.4367, label: "Iguazu Falls, Argentina/Brazil" },
  { clue: "Torres del Paine, Patagonia, Chile",        lat: -50.9423, lng: -73.4068,  label: "Torres del Paine, Chile" },
  { clue: "Easter Island Moai (Rano Raraku), Chile",   lat: -27.1225, lng: -109.2889, label: "Easter Island Moai, Chile" },
  { clue: "Galápagos Islands (Puerto Ayora), Ecuador", lat: -0.7393,  lng: -90.3117,  label: "Galápagos Islands, Ecuador" },
  { clue: "Perito Moreno Glacier, Santa Cruz, Argentina", lat: -50.4959, lng: -73.1384, label: "Perito Moreno Glacier, Argentina" },
  { clue: "Aconcagua Summit, Mendoza, Argentina",      lat: -32.6532, lng: -70.0109,  label: "Aconcagua, Argentina" },
  { clue: "Tikal Pyramid, Petén, Guatemala",           lat: 17.2220,  lng: -89.6237,  label: "Tikal, Guatemala" },
  { clue: "Panama Canal (Miraflores Locks), Panama",   lat: 8.9981,   lng: -79.5972,  label: "Panama Canal Locks" },
  { clue: "Old Havana (Habana Vieja), Havana, Cuba",   lat: 23.1388,  lng: -82.3517,  label: "Old Havana, Cuba" },

  // ── Oceania & Pacific ────────────────────────────────────────────────────
  { clue: "Sydney Opera House, Sydney, Australia",     lat: -33.8568, lng: 151.2153,  label: "Sydney Opera House" },
  { clue: "Sydney Harbour Bridge, Sydney, Australia",  lat: -33.8523, lng: 151.2108,  label: "Sydney Harbour Bridge" },
  { clue: "Uluru (Ayers Rock), Northern Territory, Australia", lat: -25.3444, lng: 131.0369, label: "Uluru, Australia" },
  { clue: "Great Barrier Reef, Queensland, Australia", lat: -18.2871, lng: 147.6992,  label: "Great Barrier Reef, Australia" },
  { clue: "Great Ocean Road (Twelve Apostles), Victoria, Australia", lat: -38.6630, lng: 143.1050, label: "Twelve Apostles, Victoria" },
  { clue: "Kakadu National Park, Northern Territory, Australia", lat: -12.8681, lng: 132.4747, label: "Kakadu NP, Australia" },
  { clue: "Blue Mountains, New South Wales, Australia", lat: -33.7212, lng: 150.3117, label: "Blue Mountains, NSW" },
  { clue: "Sky Tower, Auckland, New Zealand",          lat: -36.8483, lng: 174.7622,  label: "Sky Tower, Auckland" },
  { clue: "Milford Sound Fjord, Fiordland, New Zealand", lat: -44.6414, lng: 167.8975, label: "Milford Sound, New Zealand" },
  { clue: "Mount Cook (Aoraki), Canterbury, New Zealand", lat: -43.5950, lng: 170.1418, label: "Aoraki/Mount Cook, NZ" },
  { clue: "Rotorua Geothermal Area, Bay of Plenty, NZ", lat: -38.1368, lng: 176.2497, label: "Rotorua, New Zealand" },
  { clue: "Hobbiton Movie Set, Matamata, New Zealand", lat: -37.8722, lng: 175.6820,  label: "Hobbiton, New Zealand" },
  { clue: "Bora Bora Lagoon, Society Islands, French Polynesia", lat: -16.5004, lng: -151.7415, label: "Bora Bora Lagoon" },
  { clue: "Pearl Harbor Memorial, Honolulu, Hawaii, USA", lat: 21.3649, lng: -157.9502, label: "Pearl Harbor, Hawaii" },
  { clue: "Waikiki Beach, Honolulu, Hawaii, USA",      lat: 21.2769,  lng: -157.8297, label: "Waikiki Beach, Hawaii" },
  { clue: "Kilauea Volcano, Big Island, Hawaii, USA",  lat: 19.4210,  lng: -155.2860, label: "Kilauea Volcano, Hawaii" },

  // ── Russia & Polar ───────────────────────────────────────────────────────
  { clue: "Saint Basil's Cathedral, Moscow, Russia",   lat: 55.7525,  lng: 37.6231,   label: "Saint Basil's Cathedral, Moscow" },
  { clue: "Kremlin (Red Square), Moscow, Russia",      lat: 55.7520,  lng: 37.6175,   label: "Kremlin/Red Square, Moscow" },
  { clue: "Hermitage Museum, Saint Petersburg, Russia", lat: 59.9398, lng: 30.3146,   label: "Hermitage Museum, St. Petersburg" },
  { clue: "Church of the Savior on Blood, St. Petersburg, Russia", lat: 59.9401, lng: 30.3287, label: "Church on Spilled Blood, St. Petersburg" },
  { clue: "Lake Baikal, Irkutsk, Russia",              lat: 53.5587,  lng: 108.1650,  label: "Lake Baikal, Russia" },
  { clue: "Trans-Siberian Railway (Circumbaikal), Russia", lat: 51.8400, lng: 104.1700, label: "Trans-Siberian Railway, Baikal" },
  { clue: "Kamchatka Volcanoes (Klyuchevskaya), Russia", lat: 56.0540, lng: 160.6438, label: "Klyuchevskaya Volcano, Kamchatka" },
  { clue: "Mount Elbrus Summit, North Caucasus, Russia", lat: 43.3550, lng: 42.4399,  label: "Mount Elbrus, Russia" },
  { clue: "Svalbard Settlement (Longyearbyen), Norway", lat: 78.2232, lng: 15.6267,   label: "Longyearbyen, Svalbard" },
  { clue: "Geirangerfjord, Møre og Romsdal, Norway",   lat: 62.1003,  lng: 7.2050,    label: "Geirangerfjord, Norway" },
  { clue: "Northern Lights (Tromsø), Troms, Norway",   lat: 69.6492,  lng: 18.9553,   label: "Tromsø, Norway (Northern Lights)" },
  { clue: "Þingvellir National Park, Iceland",         lat: 64.2559,  lng: -21.1300,  label: "Þingvellir, Iceland" },
  { clue: "Geysir Hot Spring, Haukadalur, Iceland",    lat: 64.3100,  lng: -20.3013,  label: "Geysir, Iceland" },
  { clue: "Skógafoss Waterfall, Iceland",              lat: 63.5320,  lng: -19.5108,  label: "Skógafoss, Iceland" },
  { clue: "Blue Lagoon Geothermal Spa, Grindavík, Iceland", lat: 63.8804, lng: -22.4495, label: "Blue Lagoon, Iceland" },
  { clue: "McMurdo Station, Ross Island, Antarctica",  lat: -77.8500, lng: 166.6694,  label: "McMurdo Station, Antarctica" },

  // ── Canals, Straits, Geographic wonders ─────────────────────────────────
  { clue: "Suez Canal (Ismailia), Egypt",              lat: 30.5852,  lng: 32.2654,   label: "Suez Canal, Egypt" },
  { clue: "Panama Canal (Gatun Locks), Panama",        lat: 9.2644,   lng: -79.9230,  label: "Gatun Locks, Panama Canal" },
  { clue: "Corinth Canal, Corinthia, Greece",          lat: 37.9236,  lng: 22.9972,   label: "Corinth Canal, Greece" },
  { clue: "Strait of Gibraltar Crossing, Gibraltar/Morocco", lat: 35.9870, lng: -5.3580, label: "Strait of Gibraltar" },
  { clue: "Bosphorus Strait (Bosphorus Bridge), Istanbul, Turkey", lat: 41.0467, lng: 29.0338, label: "Bosphorus Bridge, Istanbul" },
  { clue: "Dead Sea Salt Flats, Jordan",               lat: 31.5590,  lng: 35.4732,   label: "Dead Sea Shoreline, Jordan" },
  { clue: "Victoria Lake Shore, Kisumu, Kenya",        lat: 0.0917,   lng: 34.7680,   label: "Lake Victoria Shore, Kenya" },
  { clue: "Angel Falls, Bolívar, Venezuela",           lat: 5.9680,   lng: -62.5357,  label: "Angel Falls, Venezuela" },
  { clue: "Amazon River Mouth, Amapá, Brazil",         lat: -0.4653,  lng: -49.9897,  label: "Amazon River Mouth, Brazil" },
  { clue: "Nile River at Aswan Dam, Egypt",            lat: 23.9697,  lng: 32.8776,   label: "Aswan Dam, Egypt" },
  { clue: "Mekong River Delta, Cần Thơ, Vietnam",      lat: 10.0340,  lng: 105.7880,  label: "Mekong Delta, Vietnam" },
  { clue: "Rhine Falls, Schaffhausen, Switzerland",    lat: 47.6779,  lng: 8.6157,    label: "Rhine Falls, Switzerland" },
  { clue: "Plitvice Lakes, Lika-Senj, Croatia",        lat: 44.8654,  lng: 15.5820,   label: "Plitvice Lakes, Croatia" },
  { clue: "Waitomo Glowworm Caves, Waikato, New Zealand", lat: -38.2614, lng: 175.1047, label: "Waitomo Caves, New Zealand" },
  { clue: "Chocolate Hills, Bohol, Philippines",       lat: 9.7940,   lng: 124.1756,  label: "Chocolate Hills, Philippines" },
  // ── Additional Europe ────────────────────────────────────────────────────
  { clue: "Eiffel Tower (night view from Trocadéro), Paris, France", lat: 48.8614, lng: 2.2893, label: "Trocadéro, Paris" },
  { clue: "Musée d'Orsay, Paris, France",               lat: 48.8600,  lng: 2.3266,   label: "Musée d'Orsay, Paris" },
  { clue: "Château de Chambord, Loir-et-Cher, France",  lat: 47.6162,  lng: 1.5171,   label: "Château de Chambord, France" },
  { clue: "Pont du Gard Aqueduct, Nîmes, France",       lat: 43.9474,  lng: 4.5356,   label: "Pont du Gard, France" },
  { clue: "Lascaux Cave Paintings, Dordogne, France",   lat: 45.0533,  lng: 1.0768,   label: "Lascaux Caves, France" },
  { clue: "Carcassonne Medieval City, Aude, France",    lat: 43.2076,  lng: 2.3634,   label: "Carcassonne, France" },
  { clue: "Palais des Papes, Avignon, France",          lat: 43.9493,  lng: 4.8059,   label: "Palais des Papes, Avignon" },
  { clue: "Roman Colosseum at Arles, France",           lat: 43.6772,  lng: 4.6295,   label: "Arles Colosseum, France" },
  { clue: "Piazza San Marco (St. Mark's Basilica), Venice, Italy", lat: 45.4345, lng: 12.3390, label: "St. Mark's Basilica, Venice" },
  { clue: "Castel Sant'Angelo, Rome, Italy",            lat: 41.9031,  lng: 12.4663,  label: "Castel Sant'Angelo, Rome" },
  { clue: "Amalfi Cliffside Town, Campania, Italy",     lat: 40.6341,  lng: 14.6027,  label: "Amalfi, Italy" },
  { clue: "Positano Village, Campania, Italy",          lat: 40.6281,  lng: 14.4847,  label: "Positano, Amalfi Coast" },
  { clue: "Siena Cathedral (Duomo), Siena, Italy",      lat: 43.3179,  lng: 11.3298,  label: "Siena Cathedral, Italy" },
  { clue: "Mount Etna Summit, Catania, Sicily",         lat: 37.7510,  lng: 14.9934,  label: "Etna Summit, Sicily" },
  { clue: "Valley of the Temples, Agrigento, Sicily",   lat: 37.2907,  lng: 13.5878,  label: "Valley of Temples, Agrigento" },
  { clue: "Cinque Terre (Riomaggiore), Liguria, Italy", lat: 44.0997,  lng: 9.7353,   label: "Cinque Terre, Riomaggiore" },
  { clue: "Lake Como Waterfront, Como, Italy",          lat: 45.8081,  lng: 9.0852,   label: "Lake Como, Italy" },
  { clue: "Dolomites (Three Peaks), South Tyrol, Italy", lat: 46.6208, lng: 12.3010,  label: "Three Peaks of Lavaredo, Italy" },
  { clue: "Piazza del Campo, Siena, Italy",             lat: 43.3183,  lng: 11.3306,  label: "Piazza del Campo, Siena" },
  { clue: "Bernabéu Stadium, Madrid, Spain",            lat: 40.4531,  lng: -3.6883,  label: "Bernabéu Stadium, Madrid" },
  { clue: "Guggenheim Museum, Bilbao, Spain",           lat: 43.2689,  lng: -2.9340,  label: "Guggenheim Museum, Bilbao" },
  { clue: "Seville Cathedral (La Giralda), Seville, Spain", lat: 37.3861, lng: -5.9926, label: "Seville Cathedral, Spain" },
  { clue: "Córdoba Mosque-Cathedral, Córdoba, Spain",   lat: 37.8789,  lng: -4.7794,  label: "Mosque-Cathedral of Córdoba" },
  { clue: "Ronda Bridge (Puente Nuevo), Ronda, Spain",  lat: 36.7456,  lng: -5.1650,  label: "Puente Nuevo, Ronda, Spain" },
  { clue: "Gaudi's Casa Batlló, Barcelona, Spain",      lat: 41.3916,  lng: 2.1649,   label: "Casa Batlló, Barcelona" },
  { clue: "Alcázar of Segovia, Segovia, Spain",         lat: 40.9529,  lng: -4.1284,  label: "Alcázar of Segovia, Spain" },
  { clue: "Lisbon's Belém Tower, Lisbon, Portugal",     lat: 38.6916,  lng: -9.2157,  label: "Belém Tower, Lisbon" },
  { clue: "Jerónimos Monastery, Lisbon, Portugal",      lat: 38.6977,  lng: -9.2066,  label: "Jerónimos Monastery, Lisbon" },
  { clue: "Pena Palace, Sintra, Portugal",              lat: 38.7876,  lng: -9.3905,  label: "Pena Palace, Sintra" },
  { clue: "Cape St. Vincent Lighthouse, Algarve, Portugal", lat: 37.0183, lng: -8.9954, label: "Cape St. Vincent, Portugal" },
  { clue: "Douro Valley Vineyards, Porto, Portugal",    lat: 41.1496,  lng: -7.7943,  label: "Douro Valley, Portugal" },
  { clue: "Dom Luís I Bridge, Porto, Portugal",         lat: 41.1395,  lng: -8.6091,  label: "Dom Luís Bridge, Porto" },
  { clue: "Royal Palace of Amsterdam, Netherlands",     lat: 52.3731,  lng: 4.8931,   label: "Royal Palace, Amsterdam" },
  { clue: "Van Gogh Museum, Amsterdam, Netherlands",    lat: 52.3584,  lng: 4.8811,   label: "Van Gogh Museum, Amsterdam" },
  { clue: "Windmills at Kinderdijk, Netherlands",       lat: 51.8837,  lng: 4.6351,   label: "Kinderdijk Windmills, Netherlands" },
  { clue: "Bruges Market Square, Bruges, Belgium",      lat: 51.2093,  lng: 3.2247,   label: "Market Square, Bruges" },
  { clue: "Grand Place, Brussels, Belgium",             lat: 50.8467,  lng: 4.3525,   label: "Grand Place, Brussels" },
  { clue: "Château de Ghent, Ghent, Belgium",           lat: 51.0568,  lng: 3.7214,   label: "Gravensteen Castle, Ghent" },
  { clue: "The Little Mermaid Statue, Copenhagen, Denmark", lat: 55.6929, lng: 12.5993, label: "Little Mermaid, Copenhagen" },
  { clue: "Tivoli Gardens, Copenhagen, Denmark",        lat: 55.6737,  lng: 12.5681,  label: "Tivoli Gardens, Copenhagen" },
  { clue: "ABBA Museum, Stockholm, Sweden",             lat: 59.3249,  lng: 18.0980,  label: "ABBA Museum, Stockholm" },
  { clue: "Gamla Stan (Old Town), Stockholm, Sweden",   lat: 59.3249,  lng: 18.0712,  label: "Gamla Stan, Stockholm" },
  { clue: "Vasa Museum, Stockholm, Sweden",             lat: 59.3280,  lng: 18.0914,  label: "Vasa Museum, Stockholm" },
  { clue: "Vigeland Sculpture Park, Oslo, Norway",      lat: 59.9264,  lng: 10.6998,  label: "Vigeland Park, Oslo" },
  { clue: "Akershus Fortress, Oslo, Norway",            lat: 59.9079,  lng: 10.7360,  label: "Akershus Fortress, Oslo" },
  { clue: "Preikestolen (Pulpit Rock) Cliff, Norway",   lat: 58.9862,  lng: 6.1888,   label: "Pulpit Rock, Norway" },
  { clue: "Bergen Wharf (Bryggen), Bergen, Norway",     lat: 60.3975,  lng: 5.3241,   label: "Bryggen Wharf, Bergen" },
  { clue: "Urnes Stave Church, Luster, Norway",         lat: 61.2968,  lng: 7.3274,   label: "Urnes Stave Church, Norway" },
  { clue: "Helsinki Cathedral, Helsinki, Finland",      lat: 60.1700,  lng: 24.9523,  label: "Helsinki Cathedral, Finland" },
  { clue: "Suomenlinna Sea Fortress, Helsinki, Finland", lat: 60.1451, lng: 24.9880,  label: "Suomenlinna Fortress, Finland" },
  { clue: "Krak des Chevaliers Crusader Castle, Homs, Syria", lat: 34.7551, lng: 36.2947, label: "Krak des Chevaliers, Syria" },
  { clue: "Walled Old City, Dubrovnik, Croatia",        lat: 42.6412,  lng: 18.1101,  label: "Old City Walls, Dubrovnik" },
  { clue: "Diocletian's Palace, Split, Croatia",        lat: 43.5079,  lng: 16.4403,  label: "Diocletian's Palace, Split" },
  { clue: "Bay of Kotor, Montenegro",                   lat: 42.4242,  lng: 18.7686,  label: "Bay of Kotor, Montenegro" },
  { clue: "Mostar Bridge (Stari Most), Mostar, Bosnia", lat: 43.3368,  lng: 17.8151,  label: "Stari Most Bridge, Mostar" },
  { clue: "Rila Monastery, Rila, Bulgaria",             lat: 42.1337,  lng: 23.3407,  label: "Rila Monastery, Bulgaria" },
  { clue: "Transylvania (Bran Castle), Brașov, Romania", lat: 45.5139, lng: 25.3668,  label: "Bran Castle (Dracula), Romania" },
  { clue: "Painted Monasteries, Bucovina, Romania",     lat: 47.5321,  lng: 25.7313,  label: "Sucevița Monastery, Romania" },
  { clue: "Tallinn Old Town, Tallinn, Estonia",         lat: 59.4372,  lng: 24.7453,  label: "Tallinn Old Town, Estonia" },
  { clue: "Riga Old Town, Riga, Latvia",                lat: 56.9489,  lng: 24.1052,  label: "Riga Old Town, Latvia" },
  { clue: "Vilnius Old Town Cathedral, Vilnius, Lithuania", lat: 54.6854, lng: 25.2867, label: "Vilnius Cathedral, Lithuania" },
  { clue: "Trakai Island Castle, Trakai, Lithuania",    lat: 54.6381,  lng: 24.9334,  label: "Trakai Island Castle" },
  { clue: "Valletta Bastions, Valletta, Malta",         lat: 35.8989,  lng: 14.5146,  label: "Valletta Bastions, Malta" },
  { clue: "Ggantija Megalithic Temple, Gozo, Malta",    lat: 36.0480,  lng: 14.2671,  label: "Ggantija Temples, Malta" },
  { clue: "Acropolis of Lindos, Rhodes, Greece",        lat: 36.0918,  lng: 28.0883,  label: "Acropolis of Lindos, Rhodes" },
  { clue: "Palace of the Grand Master, Rhodes, Greece", lat: 36.4463,  lng: 28.2254,  label: "Palace Grand Master, Rhodes" },
  { clue: "Delphi Oracle Site, Phocis, Greece",         lat: 38.4824,  lng: 22.5011,  label: "Delphi Oracle Site, Greece" },
  { clue: "Olympia Ancient Site (Zeus Temple), Greece", lat: 37.6382,  lng: 21.6300,  label: "Ancient Olympia, Greece" },
  { clue: "Epidaurus Ancient Theatre, Greece",          lat: 37.5980,  lng: 23.0780,  label: "Epidaurus Theatre, Greece" },

  // ── Additional Americas ───────────────────────────────────────────────────
  { clue: "Hoover Dam, Boulder City, Nevada, USA",      lat: 36.0160,  lng: -114.7377, label: "Hoover Dam, Nevada" },
  { clue: "Antelope Canyon, Page, Arizona, USA",        lat: 36.8619,  lng: -111.3743, label: "Antelope Canyon, Arizona" },
  { clue: "Horseshoe Bend, Page, Arizona, USA",         lat: 36.8791,  lng: -111.5101, label: "Horseshoe Bend, Arizona" },
  { clue: "Bryce Canyon Hoodoos, Utah, USA",            lat: 37.6432,  lng: -112.1677, label: "Bryce Canyon, Utah" },
  { clue: "Zion Canyon (Angels Landing), Utah, USA",    lat: 37.2692,  lng: -112.9541, label: "Zion Canyon, Utah" },
  { clue: "Arches National Park, Moab, Utah, USA",      lat: 38.7330,  lng: -109.5925, label: "Arches NP, Utah" },
  { clue: "Yosemite Falls, Yosemite, California, USA",  lat: 37.7562,  lng: -119.5960, label: "Yosemite Falls, California" },
  { clue: "Half Dome, Yosemite, California, USA",       lat: 37.7459,  lng: -119.5332, label: "Half Dome, Yosemite" },
  { clue: "Death Valley (Badwater Basin), California, USA", lat: 36.2303, lng: -116.7683, label: "Badwater Basin, Death Valley" },
  { clue: "Crater Lake, Klamath, Oregon, USA",          lat: 42.9446,  lng: -122.1090, label: "Crater Lake, Oregon" },
  { clue: "Mount St. Helens Crater, Washington, USA",   lat: 46.1912,  lng: -122.1944, label: "Mount St. Helens, Washington" },
  { clue: "Glacier National Park, Montana, USA",        lat: 48.7596,  lng: -113.7870, label: "Glacier NP, Montana" },
  { clue: "Denali Summit, Alaska, USA",                 lat: 63.0692,  lng: -151.0070, label: "Denali Summit, Alaska" },
  { clue: "Kenai Fjords (Exit Glacier), Alaska, USA",   lat: 60.1864,  lng: -149.6355, label: "Exit Glacier, Alaska" },
  { clue: "Key West Lighthouse, Florida, USA",          lat: 24.5484,  lng: -81.8032,  label: "Key West Lighthouse, Florida" },
  { clue: "Cape Canaveral Launch Pad, Florida, USA",    lat: 28.5729,  lng: -80.6490,  label: "Cape Canaveral, Florida" },
  { clue: "Walt Disney World (Magic Kingdom), Orlando, USA", lat: 28.4177, lng: -81.5812, label: "Magic Kingdom, Orlando" },
  { clue: "French Quarter Jazz Street, New Orleans, USA", lat: 29.9582, lng: -90.0645,  label: "Bourbon Street, New Orleans" },
  { clue: "Harvard University, Cambridge, Massachusetts, USA", lat: 42.3770, lng: -71.1167, label: "Harvard University, Cambridge" },
  { clue: "Liberty Bell, Philadelphia, USA",             lat: 39.9493, lng: -75.1503,   label: "Liberty Bell, Philadelphia" },
  { clue: "Gateway Arch, Saint Louis, Missouri, USA",   lat: 38.6247,  lng: -90.1848,   label: "Gateway Arch, St. Louis" },
  { clue: "Crazy Horse Memorial, Black Hills, South Dakota, USA", lat: 43.8836, lng: -103.5905, label: "Crazy Horse Memorial, SD" },
  { clue: "Chaco Canyon Great House, New Mexico, USA",  lat: 36.0608,  lng: -107.9585,  label: "Chaco Canyon, New Mexico" },
  { clue: "Mesa Verde Cliff Dwellings, Colorado, USA",  lat: 37.1808,  lng: -108.4886,  label: "Mesa Verde, Colorado" },
  { clue: "Grand Prismatic Spring, Yellowstone, USA",   lat: 44.5250,  lng: -110.8384,  label: "Grand Prismatic Spring, Wyoming" },
  { clue: "Niagara Falls (American Side), New York, USA", lat: 43.0856, lng: -79.0654,  label: "Niagara Falls, New York" },
  { clue: "Parliament Buildings, Ottawa, Canada",       lat: 45.4236,  lng: -75.7009,   label: "Parliament Hill, Ottawa" },
  { clue: "Old Montreal (Notre-Dame Basilica), Montréal, Canada", lat: 45.5047, lng: -73.5563, label: "Notre-Dame Basilica, Montreal" },
  { clue: "Niagara-on-the-Lake, Ontario, Canada",       lat: 43.2553,  lng: -79.0711,   label: "Niagara-on-the-Lake, Canada" },
  { clue: "Whistler Ski Resort, BC, Canada",            lat: 50.1163,  lng: -122.9574,  label: "Whistler, British Columbia" },
  { clue: "Butchart Gardens, Victoria, BC, Canada",     lat: 48.5649,  lng: -123.4703,  label: "Butchart Gardens, Victoria BC" },
  { clue: "Capilano Suspension Bridge, Vancouver, Canada", lat: 49.3430, lng: -123.1139, label: "Capilano Bridge, Vancouver" },
  { clue: "Tulum Ruins (El Castillo), Quintana Roo, Mexico", lat: 20.2114, lng: -87.4292, label: "Tulum El Castillo, Mexico" },
  { clue: "Monte Albán Ruins, Oaxaca, Mexico",          lat: 17.0427,  lng: -96.7697,   label: "Monte Albán, Oaxaca" },
  { clue: "Copper Canyon, Chihuahua, Mexico",           lat: 27.5517,  lng: -107.4953,  label: "Copper Canyon, Chihuahua" },
  { clue: "Cenote Ik Kil, Yucatán, Mexico",             lat: 20.6853,  lng: -88.5743,   label: "Cenote Ik Kil, Mexico" },
  { clue: "Oaxacan Tree (El Tule), Santa María, Mexico", lat: 17.0461, lng: -96.6361,   label: "El Tule Tree, Oaxaca" },
  { clue: "Xochimilco Floating Gardens, Mexico City",   lat: 19.2822,  lng: -99.1009,   label: "Xochimilco, Mexico City" },
  { clue: "Cartagena Old City Walls, Cartagena, Colombia", lat: 10.4261, lng: -75.5501,  label: "Old City Walls, Cartagena" },
  { clue: "Ciudad Perdida (Lost City), Santa Marta, Colombia", lat: 11.0390, lng: -73.9260, label: "Ciudad Perdida, Colombia" },
  { clue: "Cocora Valley Wax Palms, Salento, Colombia", lat: 4.6383,   lng: -75.4758,   label: "Cocora Valley, Colombia" },
  { clue: "Angel Falls, Canaima, Venezuela",            lat: 5.9680,   lng: -62.5357,   label: "Angel Falls, Venezuela" },
  { clue: "Roraima Tepui Summit, Gran Sabana, Venezuela", lat: 5.1432, lng: -60.7631,   label: "Mount Roraima, Venezuela" },
  { clue: "Galápagos Giant Tortoise Reserve, Isabela, Ecuador", lat: -0.9752, lng: -91.3574, label: "Giant Tortoise Reserve, Galápagos" },
  { clue: "Quilotoa Crater Lake, Cotopaxi, Ecuador",    lat: -0.8643,  lng: -78.9005,   label: "Quilotoa Crater, Ecuador" },
  { clue: "Cotopaxi Volcano, Cotopaxi, Ecuador",        lat: -0.6847,  lng: -78.4370,   label: "Cotopaxi Volcano, Ecuador" },
  { clue: "Chan Chan Ruins, Trujillo, Peru",            lat: -8.1000,  lng: -79.0667,   label: "Chan Chan, Trujillo, Peru" },
  { clue: "Rainbow Mountain (Vinicunca), Cusco, Peru",  lat: -13.8133, lng: -71.3342,   label: "Rainbow Mountain, Peru" },
  { clue: "Lake Titicaca Islands (Taquile), Puno, Peru", lat: -15.7698, lng: -69.6761,  label: "Taquile Island, Lake Titicaca" },
  { clue: "Atacama Salt Flat (Salar de Atacama), Chile", lat: -23.4946, lng: -68.2267,  label: "Salar de Atacama, Chile" },
  { clue: "Marble Caves, General Carrera Lake, Chile",  lat: -46.6419, lng: -72.6660,   label: "Marble Caves, Chile" },
  { clue: "Easter Island (Ahu Tongariki Moai), Chile",  lat: -27.1254, lng: -109.2773,  label: "Ahu Tongariki, Easter Island" },
  { clue: "Iguazu Falls from Brazil Side, Foz do Iguaçu, Brazil", lat: -25.6953, lng: -54.4367, label: "Iguazu Falls, Brazil Side" },
  { clue: "Amazon River at Manaus, Amazonas, Brazil",   lat: -3.1190,  lng: -60.0217,   label: "Manaus, Amazon, Brazil" },
  { clue: "Fernando de Noronha Island, Pernambuco, Brazil", lat: -3.8549, lng: -32.4280, label: "Fernando de Noronha, Brazil" },
  { clue: "Copacabana Beach, Rio de Janeiro, Brazil",   lat: -22.9711, lng: -43.1828,   label: "Copacabana Beach, Rio" },
  { clue: "Sugarloaf Mountain Cable Car, Rio de Janeiro, Brazil", lat: -22.9488, lng: -43.1575, label: "Sugarloaf Mountain, Rio" },
  { clue: "Chapada Diamantina Waterfalls, Bahia, Brazil", lat: -12.5408, lng: -41.3354,  label: "Chapada Diamantina, Brazil" },
  { clue: "Pantanal Wetlands, Mato Grosso, Brazil",     lat: -17.7200, lng: -57.5300,   label: "Pantanal Wetlands, Brazil" },
  { clue: "Colonia del Sacramento Historic Quarter, Uruguay", lat: -34.4726, lng: -57.8444, label: "Colonia del Sacramento, Uruguay" },
  { clue: "Perito Moreno Glacier Face, Santa Cruz, Argentina", lat: -50.4959, lng: -73.1384, label: "Perito Moreno Glacier, Argentina" },
  { clue: "Quebrada de Humahuaca, Jujuy, Argentina",    lat: -23.2086, lng: -65.3480,   label: "Quebrada de Humahuaca, Argentina" },
  { clue: "Iguazú Falls Argentine Side, Misiones, Argentina", lat: -25.6874, lng: -54.4441, label: "Iguazú Falls, Argentine Side" },

  // ── Additional Africa ─────────────────────────────────────────────────────
  { clue: "Nile River at Luxor, Luxor, Egypt",          lat: 25.6956,  lng: 32.6452,   label: "Nile at Luxor, Egypt" },
  { clue: "Alexandria Library (Bibliotheca), Alexandria, Egypt", lat: 31.2086, lng: 29.9092, label: "Bibliotheca Alexandrina, Egypt" },
  { clue: "Siwa Oasis, Matruh, Egypt",                  lat: 29.2013,  lng: 25.5187,   label: "Siwa Oasis, Egypt" },
  { clue: "Djenné Grand Mosque, Ségou, Mali",           lat: 13.9050,  lng: -4.5520,   label: "Djenné Mosque, Mali" },
  { clue: "Dogon Country Cliffside Villages, Mopti, Mali", lat: 14.4200, lng: -3.2800,  label: "Dogon Cliffs, Mali" },
  { clue: "Aksum Stelae (Obelisk), Tigray, Ethiopia",   lat: 14.1258,  lng: 38.7175,   label: "Aksum Obelisk, Ethiopia" },
  { clue: "Erta Ale Lava Lake, Afar, Ethiopia",         lat: 13.6000,  lng: 40.6700,   label: "Erta Ale Volcano, Ethiopia" },
  { clue: "Danakil Depression, Afar, Ethiopia",         lat: 14.2453,  lng: 40.2989,   label: "Danakil Depression, Ethiopia" },
  { clue: "Rwenzori Mountains (Mountain of the Moon), Uganda", lat: 0.3650, lng: 29.9225, label: "Rwenzori Mountains, Uganda" },
  { clue: "Bwindi Gorilla Forest, Kanungu, Uganda",     lat: -1.0537,  lng: 29.6636,   label: "Bwindi Forest, Uganda" },
  { clue: "Volcanoes National Park, Musanze, Rwanda",   lat: -1.4673,  lng: 29.5194,   label: "Volcanoes NP, Rwanda" },
  { clue: "Kigali Genocide Memorial, Kigali, Rwanda",   lat: -1.9418,  lng: 30.0626,   label: "Kigali Genocide Memorial" },
  { clue: "Zanzibar Stone Town, Zanzibar, Tanzania",    lat: -6.1622,  lng: 39.1893,   label: "Stone Town, Zanzibar" },
  { clue: "Selous Game Reserve, Morogoro, Tanzania",    lat: -8.5000,  lng: 37.5000,   label: "Selous Game Reserve, Tanzania" },
  { clue: "Sossusvlei Dunes, Namib Desert, Namibia",    lat: -24.7321, lng: 15.3437,   label: "Sossusvlei Dunes, Namibia" },
  { clue: "Fish River Canyon, Karasburg, Namibia",      lat: -27.5614, lng: 17.6015,   label: "Fish River Canyon, Namibia" },
  { clue: "Etosha Salt Pan, Oshana, Namibia",           lat: -18.8611, lng: 16.3290,   label: "Etosha Pan, Namibia" },
  { clue: "Skeleton Coast, Kunene, Namibia",            lat: -19.4167, lng: 12.0833,   label: "Skeleton Coast, Namibia" },
  { clue: "Chobe National Park, Kasane, Botswana",      lat: -17.8003, lng: 24.9333,   label: "Chobe NP, Botswana" },
  { clue: "Drakensberg Amphitheatre, KwaZulu-Natal, SA", lat: -28.7344, lng: 28.8978,  label: "Drakensberg Amphitheatre, SA" },
  { clue: "Kruger Park (Skukuza), Limpopo, South Africa", lat: -24.9966, lng: 31.5911, label: "Skukuza, Kruger Park, SA" },
  { clue: "Wine Estates (Stellenbosch), Cape Winelands, SA", lat: -33.9321, lng: 18.8602, label: "Stellenbosch Winelands, SA" },
  { clue: "Goree Island Slave House, Dakar, Senegal",   lat: 14.6685,  lng: -17.3988,  label: "Gorée Island, Senegal" },
  { clue: "Cape Verde Volcanic Island (Fogo), Cape Verde", lat: 14.9500, lng: -24.3500, label: "Fogo Volcano, Cape Verde" },
  { clue: "Mount Cameroon (West Africa's highest), Cameroon", lat: 4.2034, lng: 9.1718, label: "Mount Cameroon, Cameroon" },
  { clue: "Saharan Rock Art, Tassili n'Ajjer, Algeria",  lat: 25.4820, lng: 8.4265,    label: "Tassili n'Ajjer, Algeria" },
  { clue: "Marrakech Medina Souks, Marrakech, Morocco",  lat: 31.6295, lng: -7.9882,   label: "Marrakech Souks, Morocco" },
  { clue: "Aït Benhaddou Kasbah, Ouarzazate, Morocco",  lat: 31.0476,  lng: -7.1317,   label: "Aït Benhaddou, Morocco" },
  { clue: "Draa Valley Palmery, Zagora, Morocco",        lat: 30.3300, lng: -5.8467,   label: "Draa Valley, Morocco" },
  { clue: "Matmata Troglodyte Homes (Star Wars), Tunisia", lat: 33.5428, lng: 9.9671,  label: "Matmata Troglodyte, Tunisia" },
  { clue: "El Djem Roman Amphitheatre, Tunisia",         lat: 35.2960, lng: 10.7066,   label: "El Djem Amphitheatre, Tunisia" },
  { clue: "Avenue of the Baobabs, Menabe, Madagascar",   lat: -20.2518, lng: 44.4182,  label: "Baobab Avenue, Madagascar" },
  { clue: "Tsingy de Bemaraha, Melaky, Madagascar",      lat: -18.7833, lng: 44.7500,  label: "Tsingy de Bemaraha, Madagascar" },
  { clue: "Mount Kenya Base (Naro Moru), Kenya",         lat: -0.1767, lng: 37.0050,   label: "Mount Kenya Base, Kenya" },
  { clue: "Amboseli Elephant Plains, Kajiado, Kenya",    lat: -2.6527, lng: 37.2600,   label: "Amboseli NP, Kenya" },
  { clue: "Lamu Island Old Town, Lamu, Kenya",           lat: -2.2694, lng: 40.9022,   label: "Lamu Old Town, Kenya" },

  // ── Additional Asia ────────────────────────────────────────────────────────
  { clue: "Great Buddha (Kotoku-in), Kamakura, Japan",  lat: 35.3355,  lng: 139.5365,  label: "Great Buddha, Kamakura" },
  { clue: "Nishiki Market, Kyoto, Japan",               lat: 35.0052,  lng: 135.7654,  label: "Nishiki Market, Kyoto" },
  { clue: "Itsukushima Shrine (Floating Torii), Miyajima, Japan", lat: 34.2969, lng: 132.3197, label: "Itsukushima Shrine, Miyajima" },
  { clue: "Okinawa Shuri Castle, Naha, Japan",          lat: 26.2172,  lng: 127.7190,  label: "Shuri Castle, Okinawa" },
  { clue: "Jigokudani Monkey Park, Nagano, Japan",      lat: 36.7340,  lng: 138.4699,  label: "Jigokudani Monkey Park, Japan" },
  { clue: "Nijo Castle, Kyoto, Japan",                  lat: 35.0142,  lng: 135.7480,  label: "Nijo Castle, Kyoto" },
  { clue: "Osaka Castle, Osaka, Japan",                 lat: 34.6873,  lng: 135.5259,  label: "Osaka Castle, Japan" },
  { clue: "Dotonbori Canal, Osaka, Japan",              lat: 34.6687,  lng: 135.5013,  label: "Dotonbori, Osaka" },
  { clue: "Taipei 101 Tower, Taipei, Taiwan",           lat: 25.0338,  lng: 121.5646,  label: "Taipei 101, Taiwan" },
  { clue: "Sun Moon Lake, Nantou, Taiwan",              lat: 23.8604,  lng: 120.9123,  label: "Sun Moon Lake, Taiwan" },
  { clue: "Taroko Gorge, Hualien, Taiwan",              lat: 24.1571,  lng: 121.6205,  label: "Taroko Gorge, Taiwan" },
  { clue: "Cheomseongdae Observatory, Gyeongju, South Korea", lat: 35.8350, lng: 129.2178, label: "Cheomseongdae Observatory, Gyeongju" },
  { clue: "Haeinsa Temple (Tripitaka), South Korea",    lat: 35.8014,  lng: 128.1027,  label: "Haeinsa Temple, South Korea" },
  { clue: "Seoraksan National Park, Gangwon, South Korea", lat: 38.1196, lng: 128.4656, label: "Seoraksan NP, South Korea" },
  { clue: "Changdeokgung Palace, Seoul, South Korea",   lat: 37.5794,  lng: 126.9910,  label: "Changdeokgung Palace, Seoul" },
  { clue: "Banpo Bridge Rainbow Fountain, Seoul, South Korea", lat: 37.5125, lng: 126.9947, label: "Banpo Bridge, Seoul" },
  { clue: "Forbidden City (South Gate), Beijing, China", lat: 39.9076,  lng: 116.3974,  label: "Tiananmen Gate, Beijing" },
  { clue: "West Lake, Hangzhou, China",                 lat: 30.2446,  lng: 120.1501,   label: "West Lake, Hangzhou" },
  { clue: "Zhangjiajie Avatar Pillars, Hunan, China",   lat: 29.3366,  lng: 110.4343,   label: "Avatar Mountains, Zhangjiajie" },
  { clue: "Guilin Reed Flute Cave, Guilin, China",      lat: 25.3034,  lng: 110.2720,   label: "Reed Flute Cave, Guilin" },
  { clue: "Leshan Giant Buddha, Sichuan, China",        lat: 29.5446,  lng: 103.7721,   label: "Leshan Giant Buddha, China" },
  { clue: "Jiuzhaigou Valley Lakes, Sichuan, China",    lat: 33.1198,  lng: 103.8990,   label: "Jiuzhaigou Valley, China" },
  { clue: "Three Gorges Dam, Yichang, Hubei, China",    lat: 30.8230,  lng: 111.0040,   label: "Three Gorges Dam, China" },
  { clue: "Shanghai Tower (world's 2nd tallest), Shanghai, China", lat: 31.2357, lng: 121.5014, label: "Shanghai Tower, China" },
  { clue: "Jade Dragon Snow Mountain, Lijiang, China",  lat: 27.1063,  lng: 100.2218,   label: "Jade Dragon Snow Mountain, China" },
  { clue: "Kashgar Old City Bazaar, Xinjiang, China",   lat: 39.4729,  lng: 75.9922,    label: "Kashgar Old City, China" },
  { clue: "Dunhuang Mogao Caves, Gansu, China",         lat: 40.0410,  lng: 94.8025,    label: "Mogao Caves, Dunhuang" },
  { clue: "Lhasa Jokhang Temple, Tibet",                lat: 29.6527,  lng: 91.1187,    label: "Jokhang Temple, Lhasa" },
  { clue: "Namtso Lake, Lhasa, Tibet",                  lat: 30.7500,  lng: 90.5700,    label: "Namtso Lake, Tibet" },
  { clue: "Tiger's Nest Monastery (Paro Taktsang), Paro, Bhutan", lat: 27.4914, lng: 89.3636, label: "Tiger's Nest, Bhutan" },
  { clue: "Punakha Dzong Fortress, Punakha, Bhutan",    lat: 27.5914,  lng: 89.8638,    label: "Punakha Dzong, Bhutan" },
  { clue: "Inle Lake Floating Villages, Shan, Myanmar", lat: 20.5333,  lng: 96.9000,    label: "Inle Lake, Myanmar" },
  { clue: "Pyu Ancient Cities, Bago, Myanmar",          lat: 18.2946,  lng: 95.6566,    label: "Pyu Ancient Cities, Myanmar" },
  { clue: "Ho Chi Minh Mausoleum, Hanoi, Vietnam",      lat: 21.0369,  lng: 105.8340,   label: "Ho Chi Minh Mausoleum, Hanoi" },
  { clue: "Hue Imperial Citadel, Thừa Thiên-Huế, Vietnam", lat: 16.4698, lng: 107.5782, label: "Hue Imperial Citadel, Vietnam" },
  { clue: "Son Doong Cave (world's largest), Quảng Bình, Vietnam", lat: 17.4550, lng: 106.2880, label: "Son Doong Cave, Vietnam" },
  { clue: "Thien Mu Pagoda, Huế, Vietnam",              lat: 16.4529,  lng: 107.5414,   label: "Thien Mu Pagoda, Hue" },
  { clue: "Royal Palace Complex, Phnom Penh, Cambodia", lat: 11.5627,  lng: 104.9311,   label: "Royal Palace, Phnom Penh" },
  { clue: "That Luang Stupa, Vientiane, Laos",          lat: 17.9745,  lng: 102.6527,   label: "That Luang Stupa, Vientiane" },
  { clue: "Luang Prabang Night Market, Luang Prabang, Laos", lat: 19.8955, lng: 102.1340, label: "Luang Prabang Night Market" },
  { clue: "Phang Nga Bay (James Bond Island), Thailand", lat: 8.2730,  lng: 98.5019,    label: "Phang Nga Bay, Thailand" },
  { clue: "Chiang Rai White Temple (Wat Rong Khun), Thailand", lat: 19.8245, lng: 99.7635, label: "White Temple, Chiang Rai" },
  { clue: "Sukhothai Historical Park, Sukhothai, Thailand", lat: 17.0200, lng: 99.7050,  label: "Sukhothai Ruins, Thailand" },
  { clue: "George Town Heritage, Penang, Malaysia",     lat: 5.4164,   lng: 100.3327,   label: "George Town Heritage, Penang" },
  { clue: "Kinabalu Park (Mount Kinabalu), Sabah, Malaysia", lat: 6.0750, lng: 116.5577, label: "Mount Kinabalu, Malaysia" },
  { clue: "Brunei Omar Ali Saifuddien Mosque",          lat: 4.8906,   lng: 114.9426,   label: "Omar Ali Mosque, Brunei" },
  { clue: "Merlion Statue, Singapore",                  lat: 1.2867,   lng: 103.8545,   label: "Merlion Statue, Singapore" },
  { clue: "Gardens by the Bay Supertrees, Singapore",   lat: 1.2816,   lng: 103.8636,   label: "Supertree Grove, Singapore" },
  { clue: "Colossal Buddha Leshan, Sichuan, China",     lat: 29.5446,  lng: 103.7721,   label: "Leshan Buddha, China" },
  { clue: "Wudang Mountains Taoism, Hubei, China",      lat: 32.4044,  lng: 111.0039,   label: "Wudang Mountains, China" },
  { clue: "Penglai Pavilion (Fairyland), Shandong, China", lat: 37.8008, lng: 120.7536,  label: "Penglai Pavilion, China" },
  { clue: "Turpan Flaming Mountain, Xinjiang, China",   lat: 42.6833,  lng: 89.5167,    label: "Flaming Mountain, Xinjiang" },
  { clue: "Dazu Rock Carvings, Chongqing, China",       lat: 29.7041,  lng: 105.7239,   label: "Dazu Rock Carvings, China" },

  // ── Additional Oceania ─────────────────────────────────────────────────────
  { clue: "Bondi Beach, Sydney, Australia",             lat: -33.8914, lng: 151.2767,   label: "Bondi Beach, Sydney" },
  { clue: "Port Arthur Historic Site, Tasmania, Australia", lat: -43.1463, lng: 147.8511, label: "Port Arthur, Tasmania" },
  { clue: "Flinders Ranges Outback, South Australia",   lat: -31.3761, lng: 138.6971,   label: "Flinders Ranges, South Australia" },
  { clue: "Daintree Rainforest, Queensland, Australia", lat: -16.1700, lng: 145.4186,   label: "Daintree Rainforest, Queensland" },
  { clue: "Pinnacles Desert, Cervantes, WA, Australia", lat: -30.6027, lng: 115.1567,   label: "Pinnacles Desert, Western Australia" },
  { clue: "Wave Rock, Hyden, WA, Australia",            lat: -32.4349, lng: 118.8984,   label: "Wave Rock, Western Australia" },
  { clue: "Wilpena Pound, Flinders Ranges, Australia",  lat: -31.5285, lng: 138.6555,   label: "Wilpena Pound, South Australia" },
  { clue: "Cradle Mountain, Tasmania, Australia",       lat: -41.6375, lng: 145.9519,   label: "Cradle Mountain, Tasmania" },
  { clue: "Franz Josef Glacier, West Coast, NZ",        lat: -43.3898, lng: 170.1830,   label: "Franz Josef Glacier, NZ" },
  { clue: "Tongariro Volcanic Plateau, Waikato, NZ",    lat: -39.1329, lng: 175.6376,   label: "Tongariro Volcano, NZ" },
  { clue: "Bay of Islands, Northland, New Zealand",     lat: -35.2665, lng: 174.1046,   label: "Bay of Islands, NZ" },
  { clue: "Abel Tasman National Park, Nelson, NZ",      lat: -40.8870, lng: 172.9970,   label: "Abel Tasman NP, New Zealand" },
  { clue: "Queenstown Skyline Gondola, Otago, NZ",      lat: -45.0312, lng: 168.6626,   label: "Queenstown, New Zealand" },
  { clue: "Fiji Coral Coast, Sigatoka, Fiji",           lat: -18.1416, lng: 178.4419,   label: "Coral Coast, Fiji" },
  { clue: "Tanna Volcano (Mount Yasur), Vanuatu",       lat: -19.5200, lng: 169.4420,   label: "Mount Yasur, Vanuatu" },
  { clue: "Alofi Town, Niue Island",                    lat: -19.0556, lng: -169.9186,  label: "Alofi, Niue" },
  { clue: "Tahiti (Papeete Market), French Polynesia",  lat: -17.5334, lng: -149.5694,  label: "Papeete Market, Tahiti" },
  { clue: "Palau Blue Corner Dive Site, Pacific",       lat: 7.3264,   lng: 134.4683,   label: "Palau, Micronesia" },

  // ── Russia & Central Asia extras ─────────────────────────────────────────
  { clue: "Peterhof Palace Fountains, St. Petersburg, Russia", lat: 59.8855, lng: 29.9040, label: "Peterhof Palace, Russia" },
  { clue: "Kazan Kremlin, Kazan, Russia",               lat: 55.7992,  lng: 49.1069,    label: "Kazan Kremlin, Russia" },
  { clue: "Novodevichiy Monastery, Moscow, Russia",     lat: 55.7273,  lng: 37.5566,    label: "Novodevichiy Monastery, Moscow" },
  { clue: "Tretyakov Gallery, Moscow, Russia",          lat: 55.7415,  lng: 37.6208,    label: "Tretyakov Gallery, Moscow" },
  { clue: "Golden Ring (Suzdal Kremlin), Vladimir, Russia", lat: 56.4237, lng: 40.4451,  label: "Suzdal Kremlin, Russia" },
  { clue: "Altai Mountains (Belukha Peak), Russia",     lat: 49.8068,  lng: 86.5950,    label: "Belukha Peak, Altai, Russia" },
  { clue: "Valley of Geysers, Kamchatka, Russia",       lat: 54.4386,  lng: 160.1286,   label: "Valley of Geysers, Kamchatka" },
  { clue: "Aral Sea Eastern Shore, Uzbekistan",         lat: 43.8000,  lng: 59.5000,    label: "Aral Sea Shore, Uzbekistan" },
  { clue: "Silk Road Caravanserai, Bukhara, Uzbekistan", lat: 39.7747, lng: 64.4286,    label: "Bukhara Old City, Uzbekistan" },
  { clue: "Darvaza Gas Crater (Door to Hell), Turkmenistan", lat: 40.2526, lng: 58.4397, label: "Darvaza Gas Crater, Turkmenistan" },
  { clue: "Ashgabat White Marble City, Turkmenistan",   lat: 37.9601,  lng: 58.3261,    label: "Ashgabat, Turkmenistan" },
  { clue: "Almaty Medeo Ice Rink, Kazakhstan",          lat: 43.1570,  lng: 77.0650,    label: "Medeo, Almaty, Kazakhstan" },
  { clue: "Charyn Canyon, Almaty, Kazakhstan",          lat: 43.3622,  lng: 79.0786,    label: "Charyn Canyon, Kazakhstan" },
  { clue: "Issyk-Kul Lake, Issyk-Kul, Kyrgyzstan",     lat: 42.4500,  lng: 77.4500,    label: "Issyk-Kul Lake, Kyrgyzstan" },
  { clue: "Pamir Highway, Gorno-Badakhshan, Tajikistan", lat: 37.7667, lng: 74.5667,    label: "Pamir Highway, Tajikistan" },
  { clue: "Yurt Camp on Steppe, Orkhon Valley, Mongolia", lat: 47.2333, lng: 102.8333,  label: "Orkhon Valley, Mongolia" },
  { clue: "Gobi Desert Flaming Cliffs, Ömnögovi, Mongolia", lat: 44.1550, lng: 104.5170, label: "Flaming Cliffs, Gobi Desert" },
  { clue: "Gandantegchinlen Monastery, Ulaanbaatar, Mongolia", lat: 47.9198, lng: 106.8943, label: "Gandan Monastery, Ulaanbaatar" },

];

function getShuffledQuestions(count = 10) {
  const shuffled = [...QUESTIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
